### ISSUE TITLE
Show error message if avatar upload fails due to missing /assets/avatars/

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#1021]
https://forum.getkirby.com/t/editor-role-upload-avatar/6937/4

**Comment by luxlogica** [comment]
Guys, there have been *several* updates to Kirby since this error was filed over a year ago... You're being unusually slow in sorting this one out. And I keep getting caught in this error every time I start a new project...

Could we place an empty "avatars' folder in all the kits - not just in the starterkit, but also on plainkit, etc. - as mentioned in [this issue](https://github.com/getkirby/plainkit/issues/6) in the plainkit repo?

Alternatively, how difficult is it for us to just create the folder if it's not there? - don't we do that already with thumbs and cache?

**Comment by bastianallgeier** [comment]
✅ we finally solved this by creating the folder if it does not exist. The change is on the develop branch. A new beta for this will be released later today.
