### ISSUE TITLE
$oldPage in hook does not contain all information

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/panel#1025]
Using the `$oldPage` variable in a hook like `kirby()->hook('panel.page.update', function($page, $oldPage)` I noticed it does not contain all the information one expects.

For example it's not possible to get the template of the page before the update.

**Comment by lukasbestle** [comment]
I'm pretty sure this is because the object is cloned using `$oldPage = clone $page`.
In this case, PHP does not recursively clone the object. Attributes that are themselves objects are still referenced by the clone and will therefore change.

To fix this, we will need to add `__clone()` magic methods to every Kirby class. This method needs to make sure that all "object attributes" are cloned as well.

**Comment by lukasbestle** [comment]
I have decided to fix this now already because the fix could have been required for #1094.
The fix is on the develop branch of the core.
