### ISSUE TITLE
Kirby\Panel\Form textarea without buttons throws an error

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#1033]
I had the same issue as in the forum thread and I think it should be fixed.

https://forum.getkirby.com/t/panel-no-textarea-in-a-custom-modal-form/6293

We can add whatever fields to the `Kirby\Panel\Form` but when adding a textarea, it can't work if `buttons` is not specified.

**This does not work, throws an error**

```php
$form = new Kirby\Panel\Form(
  array(
    'testarea' => array(
      'type' => 'textarea'
    )
  )
);
echo $form;
```

**This does work:**

```php
$form = new Kirby\Panel\Form(
  array(
    'testarea' => array(
      'type' => 'textarea',
      'buttons' => false
    )
  )
);
echo $form;
```

If no `buttons` value is set, fallback to something... all buttons or no buttons, just don't break it.

**Comment by lukasbestle** [comment]
The `buttons` value defaults to `true` (all buttons). The issue is the way you are generating the form: It isn't related to any page and therefore [this line](https://github.com/getkirby/panel/blob/2.4.1/app/fields/textarea/buttons.php#L32) won't be able to run.

You need to initialize the form like this for any field that needs access to the page:

```php
$form = new Kirby\Panel\Form(
  array(
    'textarea' => array(
      'type' => 'textarea',
      'model' => $somePageObject
    )
  )
);
echo $form;
```
