### ISSUE TITLE
Changing the url-appendix in a non-default language will save translate:false fields to the content txt

### ISSUE THREAD

**Issue by d23levin** [getkirby/panel#1056]
Follow up of https://forum.getkirby.com/t/updating-a-translate-false-panel-field-fails-if-url-key-is-set/7688

As long as the url-appendix is not changed, the non-default language version of a page will not contain fields set to _translate: false_ in the blueprint.

Changing the url-key for non-default language will add the URL-Key field as expected, but also all other fields including the _translate: false_ fields to the text file in the content folder.

Changing the default language content won't be saved to the _translate: false_ fields of the non-default language content, as long as you click save in the non-default language editor.

Tested with fresh pulled kirby-langkit Version 2.4.1

**Comment by d23levin** [comment]
Is this a bug?

**Comment by lukasbestle** [comment]
Sorry for the delay, I missed this issue.
We will look into this.

**Comment by lukasbestle** [comment]
It turns out this is quite a difficult bug:

- The `Url-Key` field gets [set using `$page->update()`](https://github.com/getkirby/panel/blob/2.5.5/app/src/panel/models/page.php#L258-L260).
- The untranslatable fields get cleared [when serializing the form](https://github.com/getkirby/panel/blob/2.5.5/app/src/panel/form.php#L189-L196).

Since there is no form when setting the `Url-Key`, that operation can't know which fields are untranslatable. @distantnative, do you know a solution?

**Comment by lukasbestle** [comment]
Unfortunately this is a bug we can't fix in Kirby 2 because of the issues I mentioned above. As Kirby 3 is a complete rewrite, it will hopefully not have this issue anymore.
