### ISSUE TITLE
Page reordering broken in 2.5.9

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#1138]
https://forum.getkirby.com/t/kirby-2-5-9-panel-page-re-ordering-broken/9868

Looks like this happens as soon as you add a tenth visible child, with 9 children, seems to be ok.

**Comment by HashandSalt** [comment]
Seems it happens even if you re-order the pages manually in the filesystem (ie with finder) and go back into the panel. I think i edited and saved one article in the panel after manually ordering and it reshuffled all the pages out of order again.

**Comment by texnixe** [comment]
Seems to happen with image sorting as well: https://forum.getkirby.com/t/manual-sorting-images-problem-with-kirby-2-5-9/9876

**Comment by lukasbestle** [comment]
Oh no. :(
I will take a look at this very soon.

**Comment by texnixe** [comment]
This is not really a panel issue, but caused by changes in the toolkit, as far as I can see by changes in the collection class.

**Comment by Foddy** [comment]
Any news regarding this issue?

**Comment by lukasbestle** [comment]
It was indeed the refactored `$collection->sortBy()` method. To fix sorting of strings with international characters like German Umlauts, I had implemented locale-based sorting. But it turns out that locale-based sorting (in contrast to regular sorting) doesn't respect the order of numbers. `10` was right behind `1`, not behind `9`. That of course broke everything.

This is one reason why I sometimes hate PHP. Logically the behavior should be exactly the opposite, but "regular sorting" is the more robust solution, so I have changed the default back. However it is still possible to pass custom flags if you need locale sorting for a specific use-case.

So end of the story: Fixed on the develop branch of the Toolkit for the next release. You can change the one line in your installation to get the fix already now.

**Comment by eXpl0it3r** [comment]
Is there something that needs to be adjusted, because this doesn't fix the problem for me?

I've checked out the develop branch as this made it impossible to manage one website.  Yet, when I for example move the first page to the second position, then there will be changes further down. And when I then move the new first page again to the second place, the page will be put at a random location.

Maybe this is not directly related but it makes the ordering unusable and thus my current website setup.

![2018-03-16_03-56-16](https://user-images.githubusercontent.com/920861/37501299-fec4f412-28cd-11e8-9481-99af7d9ec14c.gif)
