### ISSUE TITLE
Call to undefined function abeautifulsite\imagecreatefrompng() in ? on line 1082

### ISSUE THREAD

**Issue by pichfl** [getkirby/panel#129]
This error comes up on a page with 5 files (4 pdf, 1 png) with Apache running on Mac OS X when I try to view all files of a page (which is rather unfortunate as I really like the new files sorting function)

**Comment by chbach** [comment]
If someone comes across this error again – you have to get a new package of php 5.5 or higher since GDLib with png is not included in Yosemite’s built-in php. So use brew or the following sh installer to get a new version

`curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6` and add `export PATH=/usr/local/php5/bin:$PATH`to your profile file.

**Comment by clamey** [comment]
Thanks for the follow up @chbach !

**Comment by tart2000** [comment]
I'm having the same problem with Yosemite 10.10.3 and Kirby 2.1 running locally. 
@chbach I ran the command line, but what do you call the 'profile file' ? 
Thanks !

**Comment by chbach** [comment]
@tart2000 depends on your shell. If you use the default shell on OS X, it is probably your `.bash_profile` or `.bashrc` located in your home folder. 
Check <http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html> for the difference between the two. 

If you use a different shell e.g. ZSH, it would be the `.zshrc`.

**Comment by tart2000** [comment]
Thanks @chbach ! 
It's all working fine now.
