### ISSUE TITLE
Error "The page could not be found" occurs after changing title and hitting backspace

### ISSUE THREAD

**Issue by RHansmann** [getkirby/panel#173]
Error is reproducable with each page using title field:

Change title field
Save the changes
Use Backspace key to return

**Comment by distantnative** [comment]
Since Kirby doesn't keep a history of page UIDs or something, I can't think of a way to route to the actual page. But maybe, if a page isn't found in general, we could look up if the intended parent page actually exists and, if so, redirect to the subpages overview of that parent page.

In `panel/app/controllers/views/pages.php` add an elseif-clause at line 260, like:
```php
    } elseif ($parent = array_slice(explode('/', $id), -2, 1)[0] and page($parent)) {
      go(panel()->urls()->index().'/'.purl('subpages/index/' . $parent));
```

Problem atm: `panel()->urls()->index().'/'.purl('subpages/index/' . $parent)` gets me the right URL. However the `go()`method only leads to a full grey page.

What do you think in general about that semi-solution?... well, rather a way to make it a little smoother.

**Comment by bastianallgeier** [comment]
Ok, I found a work-around for this which will bring you to the parent page correctly.
