### ISSUE TITLE
No Save Button when blueprint has no fields

### ISSUE THREAD

**Issue by servicethinker** [getkirby/panel#183]
If you have a blueprint with no fields (e.g. for structuring) you don't need a [Save]-Button

**Comment by distantnative** [comment]
Seems to be fixed in the 2.1 beta:

![screen shot 2015-04-28 at 12 57 57](https://cloud.githubusercontent.com/assets/3788865/7368233/42ca68ec-eda6-11e4-958b-8ca38ebaa87a.png)

![screen shot 2015-04-28 at 12 58 06](https://cloud.githubusercontent.com/assets/3788865/7368236/4502594e-eda6-11e4-9b4c-a0f0716e880f.png)
