### ISSUE TITLE
Radio options as Yes & No

### ISSUE THREAD

**Issue by skifreak** [getkirby/panel#258]
`Yes` or `No` as the labels for radio options are displayed as `1` and ` `

![image](http://cl.ly/image/0E1R053L0F0X/Image%202014-10-19%20at%2011.30.42%20PM.png)

Putting quotes around them, `"Yes"`, `"No"`, does the trick:

![image](http://cl.ly/image/2y2W3W2i0O2w/Image%202014-10-19%20at%2011.32.11%20PM.png)

Lastly, `default: false` does not default to false

**Comment by ian-cox** [comment]
On a similar note, I'm trying to set the default value of a number field to 0.

I'd like it to echo 0 by default or another integer if specified.

<pre>
  amount:
    label: Amount
    type: number
    default: 0
</pre>


Thanks!

**Comment by bastianallgeier** [comment]
I think this is a yaml issue. try default: "0"

**Comment by ian-cox** [comment]
I saw the earlier post and gave <code>"0"</code> a try but I still haven't been able to get the field to default to 0.

Setting the field to 0 and hitting save manually saves the field as expected.

and of course setting it to <code>default: 1</code> works find with any other integer.

Could it be because zero is not an integer?

![defaults2](https://cloud.githubusercontent.com/assets/4325127/5765617/f1c03932-9cc8-11e4-9c8c-260a9f21220f.gif)

**Comment by lukasbestle** [comment]
I haven't looked at the code that is responsible for this, but my guess is that it's because of a use of `empty()` (`empty("0")` is `true`, meaning a zero is considered to be empty).

**Comment by ian-cox** [comment]
I was just reading a little more about that.
<pre>
The following things are considered to be empty:

"" (an empty string)
0 (0 as an integer)
"0" (0 as a string)
NULL
FALSE
array() (an empty array)
var $var; (a variable declared, but without a value in a class)
</pre>

**Comment by lukasbestle** [comment]
Exactly. ;)

**Comment by ian-cox** [comment]
I'm just going to work around the issue in my template file.
<pre>
if(!$page->amount()->empty()):
   echo $page->amount();
else:
   echo "0";
endif; 
</pre>
