### ISSUE TITLE
Configure blueprint for Users

### ISSUE THREAD

**Issue by xypaul** [getkirby/panel#273]
Is there currently a way to add additional fields to the user blueprint?
![screenshot 2014-10-29 14 17 51](https://cloud.githubusercontent.com/assets/2549828/4834779/1038a250-5fb1-11e4-87d7-7d48928828b5.png)

This would be really useful to add author information (think Twitter profile etc..) onto a blogpost. I've previously done it like this - (http://getkirby.com/blog/author-system), but yeah would be much nicer if I could just add some more fields to the user :smile:

**Comment by Thomas-Lebeau** [comment]
:+1:

**Comment by dervondenbergen** [comment]
Is this now already in Kirby 2.1?

**Comment by distantnative** [comment]
No, it's not in the 2.1 release.

**Comment by distantnative** [comment]
@bastianallgeier how about using for `user.add` only the default fields (which I would see as defined fixed by the panel itself and the blueprints only add more fields to it). so only showing the blueprint fields on `user.edit`. Instead of redirecting to the user overview after adding a new user, we could redirect it directly to the `user.edit` view for the newly added user. So that then people could directly edit/add data for the additional blueprint fields.

For the `user.edit` view: I put a `reload` in the multiselect field (https://github.com/distantnative/panel/commit/e467d2bc79f0897411918ee8ffb526bc885501b2) - the idea would be that when the user role(s) are changed, the form get's submitted automatically and, thus, the respective blueprint fields for the newly role(s) selection will be shown.

If we add multiple roles per user to the panel (other issue/idea), we would need to think about what blueprint fields to show tho.

**Comment by distantnative** [comment]
On basis of the current multirole pull request, I tried a first implementation: https://github.com/distantnative/panel/commit/0ef757124b9ef9f785b2f76a9326e4ab6c49852b

`site/blueprints/users/admin.php`:
```
<?php if(!defined('KIRBY')) exit ?>

fields:
  text:
    label: Text
    type:  textarea
  birthday:
    label: Birthday
    type: date
```

It also work with multiple roles, but fields with the same name will replace each other - so the last loaded role/blueprint can overwrite earlier ones.

**Comment by byybora** [comment]
+1 When will release this feature? I'm looking forward :laughing:

**Comment by FabianSperrle** [comment]
Any news on this? Would be an amaaaaaazing feature :)

**Comment by xypaul** [comment]
Yeah when is this coming out?

**Comment by bastianallgeier** [comment]
I finally added this to the decruft branch \o/

**Comment by afbora** [comment]
Great news! @bastianallgeier  So this feature about only `users` or `users` and `roles`?

**Comment by bastianallgeier** [comment]
Roles have been here for a while, but without permissions. Permissions might need a bit more. They are just very tricky in terms of not introducing new bugs.
