### ISSUE TITLE
Use built in popups for custom fields

### ISSUE THREAD

**Issue by balintgaspar** [getkirby/panel#355]
Hello @bastianallgeier !

Can I use built in popup or modal for my custom field? If yes , Where can I find a documentation for this?

Thanks, Balint

**Comment by ljacobs-sml** [comment]
A popup modal option isn't available, nor have I seen any documentation (official or third party) on adding such a thing. You'd have to add the javascript/jquery/css assets to your custom field to support this. Since the panel loads jquery by default, this shouldn't be that difficult. You could write your own or integrate an existing jquery plugin.

http://getkirby.com/docs/panel/custom-form-fields#adding-field-assets
