### ISSUE TITLE
Blueprints ignored when setting different language as default

### ISSUE THREAD

**Issue by joernba** [getkirby/panel#364]
Hi,
when I set a different language as default (changing the setting on a working multilang site) blueprints are ignored in the panel and many pages don't display correctly. Is this a known issue or am I missing something? Is it not possible to change the default language once set?

**Comment by ljacobs-sml** [comment]
I had a site with no language specified. I later changed it to specify english as default, and when making panel changes it started creating templatename.en.txt instead of templatename.txt for the content files.

When I'd load the panel, it would look as if I hadn't changed anything because it was showing the contents of the original templatename.txt. I had to go and clean up the content files to erase old templatename.txt versions or rename them to include the .en.

I'm not sure if this is related to your issue, but you can double check that all the correct content .txt files exist for each language and that there's no ambiguous/undefined language versions.

**Comment by joernba** [comment]
Thanks for your reply.
I had the same issue as you had, but this is different. The blueprint file is completely ignored. I can't see the fields defined in the blueprint file. There's just the title and a text area.

**Comment by ljacobs-sml** [comment]
Have you checked all the indentation to confirm it's using all spaces and no tabs? That can break all the fields that follow the tab.

**Comment by joernba** [comment]
I might have found the reason for the issue. In some sections there were no text files for the new default language (in this case I switched from English to Italian as the default language). I guess that without a text file in the default language the panel somehow ignores blueprint files.
