### ISSUE TITLE
New field methods do not work with structured fields?

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#377]
Don't know if this has been mentioned before, but if I try to use html() or kirbytext() methods on a yaml-field, the page throws an error  whereas the old Kirby way if putting the method, i.e. kirbytext($structure['field'] works. It's probably got to do with the fact that yaml-fields do not return an object but a simple string and as a result putting images as a kirbytag don't work either?

**Comment by bastianallgeier** [comment]
Do you still get this problem with the nightly build? html() and kirbytext() shouldn't normally have any issues with plain strings.

**Comment by bastianallgeier** [comment]
@texnixe Did you have a chance to try this again?

**Comment by texnixe** [comment]
Even with the beta build I get an error message.

If I use something like this: <?php echo $profile['name']->html(); ?> in my template, the result is:

Fatal error: Call to a member function html() on string in

While this <?php echo html($profile['name']); ?> works perfectly.

LG
Sonja



Technische Kommunikation & Webdesign
sonja broda
robert-koch-straße 19c
55129 mainz
mobil | 0176 61633048
mail | info@texniq.de
net | www.texniq.de

**Comment by distantnative** [comment]
I just wanted to fix this, but then realized: I don't think this is an actual bug. The structured field is basically only an array, `$profile['name']` only a string element of that array. I don't think there is a way to apply Kirbytext methods to things that are not a FieldAbstract object of Kirby. At least not in the `___->kirbytext()` way. Using it with `kirbytext($profile['name'])` should still work (and @texnixe said so).

So I might be just overseeing something, but it occurs to me that this cannot be solved due to the different nature of the element and the method. Other thoughts?

**Comment by bastianallgeier** [comment]
you are right! since this is a simple php array you can use the helper functions but not the field methods. Sorry for not making it clearer in the first place.
