### ISSUE TITLE
Browsersync breaks the panel

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/panel#518]

**Comment by danielguillan** [comment]
I used to have a problems accessing the panel while using Browsersync but with the latest version of both Kirby and Browsersync everything seems works like a charm. 

What problems are you seeing?

**Comment by danielsutp** [comment]
I had the problem in the first place and replaced the Kirby and Panel folders in case I'd broken something, but I did't check Browsersync as it had been working fine for a couple of weeks and I hadn't changed any of my build tasks. 

Turns out all I had to do was reinstall Browsersync and it's back to normal...
