### ISSUE TITLE
Create & Edit button on creation modal feature request

### ISSUE THREAD

**Issue by afbora** [getkirby/panel#558]
`Create & Edit` button would be more practical, quick and fast action near of `Cancel` and `Create` button In creating page modal.

Most of the time after created page i forced to search the page on sidebar and click to edit. I think, `Create and Edit` button more useful. What do you think?

**Comment by bastianallgeier** [comment]
This is a very good idea!!

**Comment by DavidUnzue** [comment]
As I see it, this could be implemented in two ways:

## Approach 1
Same as @afbora explained, using just an extra "Create & Edit" button within the new page modal. However this approach requires 2 steps for editing the new page:
1. Click on "Add page" and modal pops up.
2. Click on "Create & Edit" button and the editing interface for the new page opens.

## Approach 2
Provide just a unique button for both page creation and editing in just one step, i.e. as soon as you click the add button, you are redirected to the page creation form, instead of first filling in a modal form with the title and then being redirected.
From the UX point of view, this could be a better approach. However, I'm not aware if this could mess up things in the core architecture of the panel.

Refer to [this topic in the Kirby Forum](http://forum.getkirby.com/t/redirect-after-page-creation-using-hook/2031)

**Comment by bastianallgeier** [comment]
This is now implemented in the new beta for the new release on the develop branch.

**Comment by afbora** [comment]
@bastianallgeier on 2.2.2 version, i couldnt find this feature? Is this removed?
