### ISSUE TITLE
Error message when trying to update page if panel.page.visibility set to false in role permissions.

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#989]
https://forum.getkirby.com/t/role-permission-i-e-panel-page-visibility/6230/20

Changes are saved to file in spite of the error message, though.

**Comment by Mattrushka** [comment]
I guess this related?!?

**Behaviour** 
When I specify that 
a) a certain user-role can update specific templates 
b) disallow the user to change visibility 
```
'panel.page.update' => function() {
      return $this->target()->page()->template() === 'mytemplate';
 },
panel.page.visibility => false
```
the user is not able to edit the template anymore but changes are saved anyway. 
And I would not expect that `panel.page.visibility => false` overrides the `'panel.page.update'` functionality because this means that I cannot have both settings together.

**Comment by samuba** [comment]
No intentions to fix this? It's pretty ugly because there are only two solutions, that I see, right now:
- setting `panel.page.visibility` to `true` for users that should not have that permission
- leaving users with the very irritating popup

**Comment by lukasbestle** [comment]
We always have the intention to fix bugs. It's just that we can't fix all of them. :)
But I will take a look at it. Maybe it's a typo in the code somewhere.

**Comment by lukasbestle** [comment]
Unfortunately I can't find a simple fix. We will however rewrite the permissions feature in Kirby 3, which will probably fix this issue.
